# Generated by Django 6.0.4 on 2026-04-28 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Habitacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Habitació',
                'verbose_name_plural': 'Habitacions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Personatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Personatge',
                'verbose_name_plural': 'Personatges',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Solucio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('resolta', models.BooleanField(default=False)),
                ('temps_resolucio', models.IntegerField(blank=True, null=True)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluedo.arma')),
                ('habitacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluedo.habitacio')),
                ('personatge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluedo.personatge')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solucions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solució',
                'verbose_name_plural': 'Solucions',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encert_personatge', models.BooleanField(default=False)),
                ('encert_arma', models.BooleanField(default=False)),
                ('encert_habitacio', models.BooleanField(default=False)),
                ('correcte', models.BooleanField(default=False)),
                ('creat_en', models.DateTimeField(auto_now_add=True)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluedo.arma')),
                ('habitacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluedo.habitacio')),
                ('personatge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluedo.personatge')),
                ('solucio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='cluedo.solucio')),
            ],
            options={
                'verbose_name': 'Intent',
                'verbose_name_plural': 'Intents',
                'ordering': ['creat_en'],
            },
        ),
    ]
