# Generated by Django 5.2.8 on 2026-02-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de tú héroe', max_length=100)),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('clase', models.CharField(max_length=50)),
                ('nivel', models.IntegerField(default=1)),
                ('punts_de_vida', models.IntegerField(verbose_name='HP')),
                ('fuerza', models.IntegerField(default=10)),
                ('destreza', models.IntegerField(default=10)),
                ('constitucion', models.IntegerField(default=10)),
                ('inteligencia', models.IntegerField(default=10)),
                ('sabiduria', models.IntegerField(default=10)),
                ('carisma', models.IntegerField(default=10)),
                ('inventario', models.IntegerField(default=10)),
            ],
        ),
    ]
