# Generated by Django 5.2.8 on 2026-02-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaje',
            old_name='punts_de_vida',
            new_name='vida',
        ),
    ]
